<script lang="ts">
  import Breadcrumb from '@fex-design/svelte/primitive/breadcrumb'
  import Card from '@fex-design/svelte/ui/card'
  import ClassicBreadcrumb from './classic-breadcrumb.svelte'
  import CapsuleBreadcrumb from './capsule-breadcrumb.svelte'
  import DropdownDemo from './dropdown-demo.svelte'
  import ParallelogramBreadcrumb from './parallelogram-breadcrumb.svelte'
  import RibbonBreadcrumb from './ribbon-breadcrumb.svelte'
</script>
<main class="min-h-screen bg-secondary-background px-page-padding py-space-xl"><div class="mx-auto w-full max-w-5xl space-y-space-xl"><header><a class="text-sm text-muted-foreground hover:text-foreground" href="/">Back home</a><h1 class="mt-space-md text-2xl font-semibold text-foreground">Breadcrumb</h1><p class="mt-space-md text-sm text-muted-foreground">Composable navigation trails with links, current pages, custom separators and menu triggers.</p></header><div class="space-y-space-xl"><Card title="Classic" description="Links and the current page use different semantics."><ClassicBreadcrumb /></Card><Card title="Custom separator" description="The separator can be any text or icon."><ClassicBreadcrumb separator="-&gt;" /></Card><Card title="Capsule" description="Connected rounded segments inspired by the reference style."><CapsuleBreadcrumb /></Card><Card title="Ribbon" description="Pointed segments with overlap and a closed final edge."><RibbonBreadcrumb /></Card><Card title="Parallelogram" description="Angled segments with shared overlap."><ParallelogramBreadcrumb /></Card><Card title="Ellipsis and dropdown trigger" description="Ellipsis is presentational; popup behavior stays with the caller."><Breadcrumb part="root"><Breadcrumb part="list"><Breadcrumb part="item"><Breadcrumb part="link" href="/">Workspace</Breadcrumb></Breadcrumb><Breadcrumb part="separator">/</Breadcrumb><Breadcrumb part="item"><DropdownDemo /></Breadcrumb><Breadcrumb part="separator">/</Breadcrumb><Breadcrumb part="item"><Breadcrumb part="link" href="/projects">Projects</Breadcrumb></Breadcrumb><Breadcrumb part="separator">/</Breadcrumb><Breadcrumb part="item"><Breadcrumb part="page">Quarterly plan</Breadcrumb></Breadcrumb></Breadcrumb></Breadcrumb></Card></div></div></main>
