import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'

@Component({
  selector: 'fex-home',
  imports: [RouterLink],
  host: { class: 'block' },
  templateUrl: './home.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent {
  protected readonly componentLinks = [
    { to: '/auto-complete', label: 'AutoComplete' },
    { to: '/carousel', label: 'Carousel' },
    { to: '/button', label: 'Button' },
    { to: '/calendar', label: 'Calendar' },
    { to: '/card', label: 'Card' },
    { to: '/checkbox', label: 'Checkbox' },
    { to: '/collapse', label: 'Collapse' },
    { to: '/context-menu', label: 'ContextMenu' },
    { to: '/dialog', label: 'Dialog' },
    { to: '/drawer', label: 'Drawer' },
    { to: '/dropdown', label: 'Dropdown' },
    { to: '/data-table', label: 'Data Table' },
    { to: '/date-picker', label: 'DatePicker' },
    { to: '/alert', label: 'Alert' },
    { to: '/badge', label: 'Badge' },
    { to: '/breadcrumb', label: 'Breadcrumb' },
    { to: '/empty', label: 'Empty' },
    { to: '/form', label: 'Form' },
    { to: '/input', label: 'Input' },
    { to: '/input-number', label: 'InputNumber' },
    { to: '/input-otp', label: 'InputOTP' },
    { to: '/kbd', label: 'Kbd' },
    { to: '/listbox', label: 'Listbox' },
    { to: '/menu', label: 'Menu' },
    { to: '/mentions', label: 'Mentions' },
    { to: '/pagination', label: 'Pagination' },
    { to: '/popover', label: 'Popover' },
    { to: '/radio', label: 'Radio' },
    { to: '/qrcode', label: 'QRCode' },
    { to: '/rate', label: 'Rate' },
    { to: '/spinner', label: 'Spinner' },
    { to: '/slider', label: 'Slider' },
    { to: '/scrollbar', label: 'Scrollbar' },
    { to: '/select', label: 'Select' },
    { to: '/cascader', label: 'Cascader' },
    { to: '/switch', label: 'Switch' },
    { to: '/table', label: 'Table' },
    { to: '/tabs', label: 'Tabs' },
    { to: '/tag', label: 'Tag' },
    { to: '/steps', label: 'Steps' },
    { to: '/timeline', label: 'Timeline' },
    { to: '/toggle', label: 'Toggle' },
    { to: '/toast', label: 'Toast' },
    { to: '/sortable', label: 'Sortable' },
    { to: '/interactions', label: 'Interactions' },
    { to: '/resizable', label: 'Resizable' },
    { to: '/textarea', label: 'Textarea' },
    { to: '/theme-provider', label: 'ThemeProvider' },
    { to: '/time-picker', label: 'TimePicker' },
    { to: '/tooltip', label: 'Tooltip' },
    { to: '/tour', label: 'Tour' },
    { to: '/tree', label: 'Tree' },
    { to: '/tree-select', label: 'TreeSelect' },
    { to: '/transfer', label: 'Transfer' },
    { to: '/upload', label: 'Upload' },
    { to: '/watermark', label: 'Watermark' },
    // eslint-disable-next-line unicorn/no-array-sort -- this literal is newly created and not shared.
  ].sort((left, right) => left.label.localeCompare(right.label))
}
