<script setup lang="ts">
import { FieldContent, FieldControl, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldRequiredIndicator, FieldRoot, FieldSeparator, FieldSet, FieldTitle } from '@fex/components-vue/primitive/field'
import { Form as FormHost, useForm } from '@fex/components-vue/primitive/form'
import { InputControl, InputRoot } from '@fex/components-vue/primitive/input'
import Button from '@fex/components-vue/ui/button'
import Card from '@fex/components-vue/ui/card'
import { Checkbox } from '@fex/components-vue/ui/checkbox'
import { ref } from 'vue'

const locations = { 浙江: ['杭州', '宁波', '温州'], 江苏: ['南京', '苏州', '无锡'], 广东: ['广州', '深圳', '珠海'] } as const
type Province = keyof typeof locations
const selectClassName = 'h-9 w-full rounded-md border border-border bg-background px-3 text-sm text-foreground outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-50'
const result = ref('尚未提交')
const instanceResult = ref('点击按钮读取或设置字段值')

const form = useForm({ defaultValues: { account: '', password: '', remember: false }, onSubmit: async ({ value }) => { await new Promise((resolve) => setTimeout(resolve, 300)); result.value = `登录：${JSON.stringify(value)}` } })
const validationForm = useForm({ defaultValues: { username: '', password: '', confirmPassword: '' }, onSubmit: ({ value }) => { result.value = `校验：${JSON.stringify(value)}` } })
const dynamicForm = useForm({ defaultValues: { nicknameRequired: true, nickname: '' }, onSubmit: ({ value }) => { result.value = `动态规则：${JSON.stringify(value)}` } })
const cascadeForm = useForm({ defaultValues: { province: '浙江' as Province, city: '杭州' }, onSubmit: ({ value }) => { result.value = `级联：${JSON.stringify(value)}` } })
const scrollForm = useForm({ defaultValues: { note: '', deliveryAddress: '' }, onSubmit: ({ value }) => { result.value = `长表单：${JSON.stringify(value)}` } })
const instanceForm = useForm({ defaultValues: { source: '来自 Form defaultValues', nickname: '' }, onSubmit: ({ value }) => { result.value = `实例方法：${JSON.stringify(value)}` } })
const layoutForm = useForm({ defaultValues: { vertical: '', horizontal: '', responsive: '' } })
const preferencesForm = useForm({ defaultValues: { productUpdates: false, securityAlerts: true }, onSubmit: ({ value }) => { result.value = `通知偏好：${JSON.stringify(value)}` } })
const nestedForm = useForm({ defaultValues: { nickname: '' }, onSubmit: ({ value }) => { result.value = `无 DOM：${value.nickname}` } })

const usernameRules = [{ required: true, message: '请输入用户名', validateTrigger: 'blur' as const }, { validateTrigger: 'change' as const, validator: async (_: unknown, value: string) => { await new Promise((resolve) => setTimeout(resolve, 200)); if (value === 'admin') throw new Error('用户名已被占用') } }]
const passwordRules = [{ required: true, message: '请输入密码' }, { min: 8, message: '密码至少 8 位' }]
const confirmPasswordRules = [{ required: true, message: '请再次输入密码' }, ({ getFieldValue }: { getFieldValue: (name: 'password') => string }) => ({ validator: (_: unknown, value: string) => value === getFieldValue('password') ? undefined : '两次密码不一致' })]
const nicknameRules = [({ getFieldValue }: { getFieldValue: (name: 'nicknameRequired') => boolean }) => ({ required: getFieldValue('nicknameRequired'), message: '请输入昵称' })]
const deliveryRules = [{ required: true, message: '请输入收货地址', validateTrigger: 'submit' as const }]
const changeProvince = (field: { handleChange: (value: Province) => void }, event: Event) => { const province = (event.target as HTMLSelectElement).value as Province; field.handleChange(province); cascadeForm.setFieldValue('city', locations[province][0]) }
const setNickname = () => instanceForm.setFieldValue('nickname', '通过 setFieldValue 设置')
const getNickname = () => { instanceResult.value = instanceForm.getFieldValue('nickname') }
</script>

<template>
  <main class="min-h-screen bg-secondary-background px-page-padding py-space-xl"><div class="mx-auto w-full max-w-5xl space-y-space-xl">
    <header class="space-y-space-md"><RouterLink class="text-sm text-muted-foreground hover:text-foreground" to="/">返回首页</RouterLink><h1 class="text-2xl font-semibold text-foreground">Form and Field primitives</h1><p class="max-w-3xl text-sm leading-6 text-muted-foreground">TanStack Form 是唯一状态源；每个示例独立展示一个可直接复用的 Form 场景。</p></header>

    <Card title="Basic form" description="必填、原生 TanStack validators、自定义 Checkbox、异步提交、重置和提交状态。"><FormHost :form="form" class="grid max-w-xl gap-space-lg">
      <component :is="form.Field" name="account" :rules="[{ required: true, message: '请输入账号', validateTrigger: 'blur' }]" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" has-description :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>账号 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" :name="field.name" autocomplete="username" placeholder="admin" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>失焦时校验必填。</FieldDescription><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <component :is="form.Field" name="password" :validators="{ onChange: ({ value }: { value: string }) => value.length >= 6 ? undefined : '密码至少 6 位' }" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>密码 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" type="password" autocomplete="current-password" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <component :is="form.Field" name="remember" v-slot="{ field, state }"><FieldRoot orientation="horizontal"><FieldControl v-slot="{ props }"><Checkbox v-bind="props" :checked="state.value" @checked-change="field.handleChange($event === true)" /></FieldControl><FieldContent><FieldLabel>记住登录状态</FieldLabel><FieldDescription>自定义控件只需显式绑定值和变更事件。</FieldDescription></FieldContent></FieldRoot></component>
      <div class="flex flex-wrap gap-space-sm"><component :is="form.Subscribe" :selector="state => [state.canSubmit, state.isSubmitting]" v-slot="value"><Button type="submit" :disabled="value[0] !== true || value[1] === true">{{ value[1] ? '提交中…' : '登录' }}</Button></component><Button type="button" variant="outline" @click="form.reset()">重置</Button></div>
    </FormHost></Card>

    <Card title="Validation timing and dependencies" description="校验时机、防抖异步校验、自定义 validator，以及密码确认依赖。"><FormHost :form="validationForm" class="grid max-w-xl gap-space-lg">
      <component :is="validationForm.Field" name="username" :rules="usernameRules" :validate-trigger="['blur', 'change']" :validate-debounce="400" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" has-description :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>用户名 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>失焦校验必填；输入 admin 触发 400ms 防抖异步校验。</FieldDescription><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <component :is="validationForm.Field" name="password" :rules="passwordRules" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>新密码 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" type="password" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <component :is="validationForm.Field" name="confirmPassword" :dependencies="['password']" :rules="confirmPasswordRules" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" has-description :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>确认密码 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" type="password" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>密码更新后，dependencies 会自动重新校验确认密码。</FieldDescription><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <Button class="w-fit" type="submit">验证</Button>
    </FormHost></Card>

    <Card title="Dynamic validation rules" description="规则工厂读取当前表单值，根据开关动态决定字段是否必填。"><FormHost :form="dynamicForm" class="grid max-w-xl gap-space-lg">
      <component :is="dynamicForm.Field" name="nicknameRequired" v-slot="{ field, state }"><FieldRoot orientation="horizontal"><FieldControl v-slot="{ props }"><Checkbox v-bind="props" :checked="state.value" @checked-change="field.handleChange($event === true)" /></FieldControl><FieldContent><FieldLabel>昵称必填</FieldLabel><FieldDescription>切换后立即改变下方字段的校验规则。</FieldDescription></FieldContent></FieldRoot></component>
      <component :is="dynamicForm.Field" name="nickname" :dependencies="['nicknameRequired']" :rules="nicknameRules" v-slot="{ field, state }"><FieldRoot :required="dynamicForm.state.values.nicknameRequired" :invalid="state.meta.isTouched && !state.meta.isValid" :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>昵称 <FieldRequiredIndicator v-if="dynamicForm.state.values.nicknameRequired" /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
      <Button class="w-fit" type="submit">检查动态规则</Button>
    </FormHost></Card>

    <Card title="Cascading fields" description="省份变化时在同一个 change 事件中更新城市，不依赖 watch。"><FormHost :form="cascadeForm" class="grid max-w-xl gap-space-lg">
      <component :is="cascadeForm.Field" name="province" v-slot="{ field, state }"><FieldRoot><FieldLabel>省份</FieldLabel><FieldControl v-slot="{ props }"><select v-bind="props" :class="selectClassName" :value="state.value" @blur="field.handleBlur" @change="changeProvince(field, $event)"><option v-for="(_, province) in locations" :key="province" :value="province">{{ province }}</option></select></FieldControl></FieldRoot></component>
      <component :is="cascadeForm.Subscribe" :selector="state => state.values.province" v-slot="province"><component :is="cascadeForm.Field" name="city" v-slot="{ field, state }"><FieldRoot has-description><FieldLabel>城市</FieldLabel><FieldControl v-slot="{ props }"><select v-bind="props" :class="selectClassName" :value="state.value" @blur="field.handleBlur" @change="field.handleChange(($event.target as HTMLSelectElement).value)"><option v-for="city in locations[province as Province]" :key="city" :value="city">{{ city }}</option></select></FieldControl><FieldDescription>城市选项由当前省份派生。</FieldDescription></FieldRoot></component></component>
      <Button class="w-fit" type="submit">提交地区</Button>
    </FormHost></Card>

    <Card title="Form instance and initialValue" description="字段 initialValue，以及 getFieldValue、setFieldValue、reset 实例方法。"><FormHost :form="instanceForm" class="grid max-w-xl gap-space-lg">
      <component :is="instanceForm.Field" name="source" v-slot="{ field, state }"><FieldRoot has-description><FieldLabel>Form 初始值</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>来自 useForm.defaultValues。</FieldDescription></FieldRoot></component>
      <component :is="instanceForm.Field" name="nickname" initial-value="来自 Field initialValue" v-slot="{ field, state }"><FieldRoot has-description><FieldLabel>字段初始值</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>initialValue 是 TanStack Field defaultValue 的语义别名。</FieldDescription></FieldRoot></component>
      <div class="flex flex-wrap gap-space-sm"><Button type="button" @click="setNickname">设置昵称</Button><Button type="button" variant="outline" @click="getNickname">读取昵称</Button><Button type="button" variant="outline" @click="instanceForm.reset()">重置</Button></div><p class="rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground" aria-live="polite">{{ instanceResult }}</p>
    </FormHost></Card>

    <Card title="Scroll to first error" description="点击顶部按钮提交长表单；校验失败后自动滚动并聚焦底部第一个错误字段。"><FormHost :form="scrollForm" :scroll-to-first-error="{ behavior: 'smooth', block: 'center', focus: true }" class="grid max-w-xl gap-space-lg">
      <Button class="w-fit" type="submit">校验并滚动到错误字段</Button><component :is="scrollForm.Field" name="note" v-slot="{ field, state }"><FieldRoot><FieldLabel>备注（选填）</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl></FieldRoot></component>
      <div class="flex min-h-[28rem] items-center justify-center rounded-md border border-dashed border-border text-sm text-muted-foreground">模拟较长的表单内容</div>
      <component :is="scrollForm.Field" name="deliveryAddress" validate-trigger="submit" :rules="deliveryRules" v-slot="{ field, state }"><FieldRoot required :invalid="state.meta.isTouched && !state.meta.isValid" has-description :has-error="state.meta.isTouched && !state.meta.isValid"><FieldLabel>收货地址 <FieldRequiredIndicator /></FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" :invalid="state.meta.isTouched && !state.meta.isValid" @value-change="field.handleChange"><InputControl v-bind="props" placeholder="此字段位于长表单底部" @blur="field.handleBlur" /></InputRoot></FieldControl><FieldDescription>这是提交失败后的定位目标。</FieldDescription><FieldError v-if="state.meta.isTouched && !state.meta.isValid" :errors="state.meta.errors" /></FieldRoot></component>
    </FormHost></Card>

    <Card title="Form layouts" description="vertical、horizontal、responsive 三种字段布局；responsive 在窄屏自动回到纵向。"><FormHost :form="layoutForm" :component="false"><FieldGroup>
      <component :is="layoutForm.Field" name="vertical" v-slot="{ field, state }"><FieldRoot orientation="vertical" has-description><FieldLabel>Vertical</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" placeholder="标签在控件上方" /></InputRoot></FieldControl><FieldDescription>默认布局。</FieldDescription></FieldRoot></component>
      <component :is="layoutForm.Field" name="horizontal" v-slot="{ field, state }"><FieldRoot orientation="horizontal" has-description><FieldLabel>Horizontal</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" placeholder="标签与控件同一行" /></InputRoot></FieldControl><FieldDescription>适合桌面端紧凑表单。</FieldDescription></FieldRoot></component>
      <component :is="layoutForm.Field" name="responsive" v-slot="{ field, state }"><FieldRoot orientation="responsive" has-description><FieldLabel>Responsive</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" placeholder="调整窗口宽度查看变化" /></InputRoot></FieldControl><FieldDescription>窄屏纵向，md 以上横向。</FieldDescription></FieldRoot></component>
    </FieldGroup></FormHost></Card>

    <Card title="Grouped fields" description="FieldSet、Legend、Group、Content、Title、Separator 组合相关字段。"><FormHost :form="preferencesForm" class="grid max-w-xl gap-space-lg"><FieldSet><FieldLegend>通知偏好</FieldLegend><FieldGroup><component :is="preferencesForm.Field" name="productUpdates" v-slot="{ field, state }"><FieldRoot orientation="horizontal"><FieldControl v-slot="{ props }"><Checkbox v-bind="props" :checked="state.value" @checked-change="field.handleChange($event === true)" /></FieldControl><FieldContent><FieldTitle>产品更新</FieldTitle><FieldDescription>接收版本与维护通知。</FieldDescription></FieldContent></FieldRoot></component><FieldSeparator /><component :is="preferencesForm.Field" name="securityAlerts" v-slot="{ field, state }"><FieldRoot orientation="horizontal"><FieldControl v-slot="{ props }"><Checkbox v-bind="props" :checked="state.value" @checked-change="field.handleChange($event === true)" /></FieldControl><FieldContent><FieldTitle>安全提醒</FieldTitle><FieldDescription>异常登录和敏感操作提醒。</FieldDescription></FieldContent></FieldRoot></component></FieldGroup></FieldSet><Button class="w-fit" type="submit">保存通知偏好</Button></FormHost></Card>
    <Card title="component=false" description="嵌套逻辑表单不输出第二个 form DOM；提交通过实例显式触发。"><FormHost :form="nestedForm" :component="false"><component :is="nestedForm.Field" name="nickname" v-slot="{ field, state }"><FieldRoot class="max-w-md"><FieldLabel>昵称</FieldLabel><FieldControl v-slot="{ props }"><InputRoot :value="state.value" @value-change="field.handleChange"><InputControl v-bind="props" @blur="field.handleBlur" /></InputRoot></FieldControl></FieldRoot></component><Button class="mt-space-md" type="button" @click="nestedForm.handleSubmit()">提交无 DOM 表单</Button></FormHost></Card>
    <Card title="Latest result" description="所有可提交示例共用的结果输出。"><pre class="overflow-auto rounded-md bg-muted p-3 text-sm text-muted-foreground">{{ result }}</pre></Card>
  </div></main>
</template>
