<script lang="ts">
  import FieldRoot from '@fex/components-svelte/primitive/field'
  import FieldControl from '@fex/components-svelte/primitive/field-control'
  import FieldLabel from '@fex/components-svelte/primitive/field-label'
  import FieldRequiredIndicator from '@fex/components-svelte/primitive/field-required-indicator'
  import FieldDescription from '@fex/components-svelte/primitive/field-description'
  import FieldError from '@fex/components-svelte/primitive/field-error'
  import FieldGroup from '@fex/components-svelte/primitive/field-group'
  import FieldSet from '@fex/components-svelte/primitive/field-set'
  import FieldLegend from '@fex/components-svelte/primitive/field-legend'
  import FieldContent from '@fex/components-svelte/primitive/field-content'
  import FieldTitle from '@fex/components-svelte/primitive/field-title'
  import FieldSeparator from '@fex/components-svelte/primitive/field-separator'
  import FormHost from '@fex/components-svelte/primitive/form'
  import { createForm } from '@fex/components-svelte/primitive/form/create-form'
  import InputRoot from '@fex/components-svelte/primitive/input'
  import InputControl from '@fex/components-svelte/primitive/input-control'
  import Button from '@fex/components-svelte/ui/button'
  import Card from '@fex/components-svelte/ui/card'
  import Checkbox from '@fex/components-svelte/ui/checkbox'

  const locations = { 浙江: ['杭州', '宁波', '温州'], 江苏: ['南京', '苏州', '无锡'], 广东: ['广州', '深圳', '珠海'] } as const
  type Province = keyof typeof locations
  const selectClass = 'h-9 w-full rounded-md border border-border bg-background px-3 text-sm text-foreground outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-50'
  let result = $state('尚未提交')
  let instanceResult = $state('点击按钮读取或设置字段值')
  const form = createForm(() => ({ defaultValues: { account: '', password: '', remember: false }, onSubmit: async ({ value }) => { await new Promise((resolve) => setTimeout(resolve, 300)); result = `登录：${JSON.stringify(value)}` } }))
  const validationForm = createForm(() => ({ defaultValues: { username: '', password: '', confirmPassword: '' }, onSubmit: ({ value }) => { result = `校验：${JSON.stringify(value)}` } }))
  const dynamicForm = createForm(() => ({ defaultValues: { nicknameRequired: true, nickname: '' }, onSubmit: ({ value }) => { result = `动态规则：${JSON.stringify(value)}` } }))
  const cascadeForm = createForm(() => ({ defaultValues: { province: '浙江' as Province, city: '杭州' }, onSubmit: ({ value }) => { result = `级联：${JSON.stringify(value)}` } }))
  const scrollForm = createForm(() => ({ defaultValues: { note: '', deliveryAddress: '' }, onSubmit: ({ value }) => { result = `长表单：${JSON.stringify(value)}` } }))
  const instanceForm = createForm(() => ({ defaultValues: { source: '来自 Form defaultValues', nickname: '' }, onSubmit: ({ value }) => { result = `实例方法：${JSON.stringify(value)}` } }))
  const layoutForm = createForm(() => ({ defaultValues: { vertical: '', horizontal: '', responsive: '' } }))
  const preferencesForm = createForm(() => ({ defaultValues: { productUpdates: false, securityAlerts: true }, onSubmit: ({ value }) => { result = `通知偏好：${JSON.stringify(value)}` } }))
  const nestedForm = createForm(() => ({ defaultValues: { nickname: '' }, onSubmit: ({ value }) => { result = `无 DOM：${value.nickname}` } }))
</script>

<main class="min-h-screen bg-secondary-background px-page-padding py-space-xl"><div class="mx-auto w-full max-w-5xl space-y-space-xl">
  <header class="space-y-space-md"><a class="text-sm text-muted-foreground hover:text-foreground" href="/">返回首页</a><h1 class="text-2xl font-semibold text-foreground">Form and Field primitives</h1><p class="max-w-3xl text-sm leading-6 text-muted-foreground">TanStack Form 是唯一状态源；每个示例独立展示一个可直接复用的 Form 场景。</p></header>

  <Card title="Basic form" description="必填、原生 TanStack validators、自定义 Checkbox、异步提交、重置和提交状态。"><FormHost {form} class="grid max-w-xl gap-space-lg">
    <form.Field name="account" rules={[{ required: true, message: '请输入账号', validateTrigger: 'blur' }]}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasDescription hasError={invalid}><FieldLabel>账号 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} autocomplete="username" placeholder="admin" onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>失焦时校验必填。</FieldDescription>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</form.Field>
    <form.Field name="password" validators={{ onChange: ({ value }) => value.length >= 6 ? undefined : '密码至少 6 位' }}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasError={invalid}><FieldLabel>密码 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} type="password" autocomplete="current-password" onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</form.Field>
    <form.Field name="remember">{#snippet children(field)}<FieldRoot orientation="horizontal"><FieldControl>{#snippet children(binding)}<Checkbox {...binding.props} checked={field.state.value} onCheckedChange={(checked) => field.handleChange(checked === true)} />{/snippet}</FieldControl><FieldContent><FieldLabel>记住登录状态</FieldLabel><FieldDescription>自定义控件只需显式绑定值和变更事件。</FieldDescription></FieldContent></FieldRoot>{/snippet}</form.Field>
    <div class="flex flex-wrap gap-space-sm"><form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>{#snippet children(state)}<Button type="submit" disabled={!state[0] || state[1]}>{state[1] ? '提交中…' : '登录'}</Button>{/snippet}</form.Subscribe><Button type="button" variant="outline" onclick={() => form.reset()}>重置</Button></div>
  </FormHost></Card>

  <Card title="Validation timing and dependencies" description="校验时机、防抖异步校验、自定义 validator，以及密码确认依赖。"><FormHost form={validationForm} class="grid max-w-xl gap-space-lg">
    <validationForm.Field name="username" validateTrigger={['blur', 'change']} validateDebounce={400} rules={[{ required: true, message: '请输入用户名', validateTrigger: 'blur' }, { validateTrigger: 'change', validator: async (_, value) => { await new Promise((resolve) => setTimeout(resolve, 200)); if (value === 'admin') throw new Error('用户名已被占用') } }]}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasDescription hasError={invalid}><FieldLabel>用户名 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>失焦校验必填；输入 admin 触发 400ms 防抖异步校验。</FieldDescription>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</validationForm.Field>
    <validationForm.Field name="password" rules={[{ required: true, message: '请输入密码' }, { min: 8, message: '密码至少 8 位' }]}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasError={invalid}><FieldLabel>新密码 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} type="password" onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</validationForm.Field>
    <validationForm.Field name="confirmPassword" dependencies={['password']} rules={[{ required: true, message: '请再次输入密码' }, ({ getFieldValue }) => ({ validator: (_, value) => value === getFieldValue('password') ? undefined : '两次密码不一致' })]}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasDescription hasError={invalid}><FieldLabel>确认密码 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} type="password" onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>密码更新后，dependencies 会自动重新校验确认密码。</FieldDescription>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</validationForm.Field><Button class="w-fit" type="submit">验证</Button>
  </FormHost></Card>

  <Card title="Dynamic validation rules" description="规则工厂读取当前表单值，根据开关动态决定字段是否必填。"><FormHost form={dynamicForm} class="grid max-w-xl gap-space-lg">
    <dynamicForm.Field name="nicknameRequired">{#snippet children(field)}<FieldRoot orientation="horizontal"><FieldControl>{#snippet children(binding)}<Checkbox {...binding.props} checked={field.state.value} onCheckedChange={(checked) => field.handleChange(checked === true)} />{/snippet}</FieldControl><FieldContent><FieldLabel>昵称必填</FieldLabel><FieldDescription>切换后立即改变下方字段的校验规则。</FieldDescription></FieldContent></FieldRoot>{/snippet}</dynamicForm.Field>
    <dynamicForm.Field name="nickname" dependencies={['nicknameRequired']} rules={[({ getFieldValue }) => ({ required: getFieldValue('nicknameRequired'), message: '请输入昵称' })]}>{#snippet children(field)}{@const required = dynamicForm.getFieldValue('nicknameRequired')}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot {required} {invalid} hasError={invalid}><FieldLabel>昵称 {#if required}<FieldRequiredIndicator />{/if}</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</dynamicForm.Field><Button class="w-fit" type="submit">检查动态规则</Button>
  </FormHost></Card>

  <Card title="Cascading fields" description="省份变化时在同一个 change 事件中更新城市，不依赖 reactive effect。"><FormHost form={cascadeForm} class="grid max-w-xl gap-space-lg">
    <cascadeForm.Field name="province">{#snippet children(field)}<FieldRoot><FieldLabel>省份</FieldLabel><FieldControl>{#snippet children(binding)}<select {...binding.props} class={selectClass} value={field.state.value} onblur={field.handleBlur} onchange={(event) => { const province = event.currentTarget.value as Province; field.handleChange(province); cascadeForm.setFieldValue('city', locations[province][0]) }}>{#each Object.keys(locations) as province}<option value={province}>{province}</option>{/each}</select>{/snippet}</FieldControl></FieldRoot>{/snippet}</cascadeForm.Field>
    <cascadeForm.Subscribe selector={(state) => state.values.province}>{#snippet children(province)}<cascadeForm.Field name="city">{#snippet children(field)}<FieldRoot hasDescription><FieldLabel>城市</FieldLabel><FieldControl>{#snippet children(binding)}<select {...binding.props} class={selectClass} value={field.state.value} onblur={field.handleBlur} onchange={(event) => field.handleChange(event.currentTarget.value)}>{#each locations[province] as city}<option value={city}>{city}</option>{/each}</select>{/snippet}</FieldControl><FieldDescription>城市选项由当前省份派生。</FieldDescription></FieldRoot>{/snippet}</cascadeForm.Field>{/snippet}</cascadeForm.Subscribe><Button class="w-fit" type="submit">提交地区</Button>
  </FormHost></Card>

  <Card title="Form instance and initialValue" description="字段 initialValue，以及 getFieldValue、setFieldValue、reset 实例方法。"><FormHost form={instanceForm} class="grid max-w-xl gap-space-lg">
    <instanceForm.Field name="source">{#snippet children(field)}<FieldRoot hasDescription><FieldLabel>Form 初始值</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>来自 createForm.defaultValues。</FieldDescription></FieldRoot>{/snippet}</instanceForm.Field>
    <instanceForm.Field name="nickname" initialValue="来自 Field initialValue">{#snippet children(field)}<FieldRoot hasDescription><FieldLabel>字段初始值</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>initialValue 是 TanStack Field defaultValue 的语义别名。</FieldDescription></FieldRoot>{/snippet}</instanceForm.Field>
    <div class="flex flex-wrap gap-space-sm"><Button type="button" onclick={() => instanceForm.setFieldValue('nickname', '通过 setFieldValue 设置')}>设置昵称</Button><Button type="button" variant="outline" onclick={() => { instanceResult = instanceForm.getFieldValue('nickname') }}>读取昵称</Button><Button type="button" variant="outline" onclick={() => instanceForm.reset()}>重置</Button></div><p class="rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground" aria-live="polite">{instanceResult}</p>
  </FormHost></Card>

  <Card title="Scroll to first error" description="点击顶部按钮提交长表单；校验失败后自动滚动并聚焦底部第一个错误字段。"><FormHost form={scrollForm} scrollToFirstError={{ behavior: 'smooth', block: 'center', focus: true }} class="grid max-w-xl gap-space-lg"><Button class="w-fit" type="submit">校验并滚动到错误字段</Button><scrollForm.Field name="note">{#snippet children(field)}<FieldRoot><FieldLabel>备注（选填）</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl></FieldRoot>{/snippet}</scrollForm.Field><div class="flex min-h-[28rem] items-center justify-center rounded-md border border-dashed border-border text-sm text-muted-foreground">模拟较长的表单内容</div><scrollForm.Field name="deliveryAddress" validateTrigger="submit" rules={[{ required: true, message: '请输入收货地址', validateTrigger: 'submit' }]}>{#snippet children(field)}{@const invalid = field.state.meta.isTouched && !field.state.meta.isValid}<FieldRoot required {invalid} hasDescription hasError={invalid}><FieldLabel>收货地址 <FieldRequiredIndicator /></FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange} {invalid}><InputControl {...binding.props} placeholder="此字段位于长表单底部" onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl><FieldDescription>这是提交失败后的定位目标。</FieldDescription>{#if invalid}<FieldError>{#snippet children()}{#each field.state.meta.errors as error}<div>{String(error)}</div>{/each}{/snippet}</FieldError>{/if}</FieldRoot>{/snippet}</scrollForm.Field></FormHost></Card>

  <Card title="Form layouts" description="vertical、horizontal、responsive 三种字段布局；responsive 在窄屏自动回到纵向。"><FormHost form={layoutForm} component={false}><FieldGroup><layoutForm.Field name="vertical">{#snippet children(field)}<FieldRoot orientation="vertical" hasDescription><FieldLabel>Vertical</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} placeholder="标签在控件上方" /></InputRoot>{/snippet}</FieldControl><FieldDescription>默认布局。</FieldDescription></FieldRoot>{/snippet}</layoutForm.Field><layoutForm.Field name="horizontal">{#snippet children(field)}<FieldRoot orientation="horizontal" hasDescription><FieldLabel>Horizontal</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} placeholder="标签与控件同一行" /></InputRoot>{/snippet}</FieldControl><FieldDescription>适合桌面端紧凑表单。</FieldDescription></FieldRoot>{/snippet}</layoutForm.Field><layoutForm.Field name="responsive">{#snippet children(field)}<FieldRoot orientation="responsive" hasDescription><FieldLabel>Responsive</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} placeholder="调整窗口宽度查看变化" /></InputRoot>{/snippet}</FieldControl><FieldDescription>窄屏纵向，md 以上横向。</FieldDescription></FieldRoot>{/snippet}</layoutForm.Field></FieldGroup></FormHost></Card>

  <Card title="Grouped fields" description="FieldSet、Legend、Group、Content、Title、Separator 组合相关字段。"><FormHost form={preferencesForm} class="grid max-w-xl gap-space-lg"><FieldSet><FieldLegend>通知偏好</FieldLegend><FieldGroup><preferencesForm.Field name="productUpdates">{#snippet children(field)}<FieldRoot orientation="horizontal"><FieldControl>{#snippet children(binding)}<Checkbox {...binding.props} checked={field.state.value} onCheckedChange={(checked) => field.handleChange(checked === true)} />{/snippet}</FieldControl><FieldContent><FieldTitle>产品更新</FieldTitle><FieldDescription>接收版本与维护通知。</FieldDescription></FieldContent></FieldRoot>{/snippet}</preferencesForm.Field><FieldSeparator /><preferencesForm.Field name="securityAlerts">{#snippet children(field)}<FieldRoot orientation="horizontal"><FieldControl>{#snippet children(binding)}<Checkbox {...binding.props} checked={field.state.value} onCheckedChange={(checked) => field.handleChange(checked === true)} />{/snippet}</FieldControl><FieldContent><FieldTitle>安全提醒</FieldTitle><FieldDescription>异常登录和敏感操作提醒。</FieldDescription></FieldContent></FieldRoot>{/snippet}</preferencesForm.Field></FieldGroup></FieldSet><Button class="w-fit" type="submit">保存通知偏好</Button></FormHost></Card>
  <Card title="component=false" description="嵌套逻辑表单不输出第二个 form DOM；提交通过实例显式触发。"><FormHost form={nestedForm} component={false}><nestedForm.Field name="nickname">{#snippet children(field)}<FieldRoot class="max-w-md"><FieldLabel>昵称</FieldLabel><FieldControl>{#snippet children(binding)}<InputRoot value={field.state.value} onValueChange={field.handleChange}><InputControl {...binding.props} onblur={field.handleBlur} /></InputRoot>{/snippet}</FieldControl></FieldRoot>{/snippet}</nestedForm.Field><Button class="mt-space-md" type="button" onclick={() => void nestedForm.handleSubmit()}>提交无 DOM 表单</Button></FormHost></Card>
  <Card title="Latest result" description="所有可提交示例共用的结果输出。"><pre class="overflow-auto rounded-md bg-muted p-3 text-sm text-muted-foreground">{result}</pre></Card>
</div></main>
